import { AgentConfig, CodeGenerationRequest, CodeGenerationResult } from '../types'
import * as fs from 'fs/promises'
import * as path from 'path'

/**
 * AI Agent Engine for code generation and manipulation
 */
export class AgentEngine {
  private config: AgentConfig
  private isInitialized = false

  constructor(config?: AgentConfig) {
    this.config = {
      model: 'default',
      maxTokens: 2000,
      temperature: 0.7,
      autoFix: true,
      ...config
    }
  }

  /**
   * Initialize the agent engine
   */
  async initialize(): Promise<void> {
    if (this.isInitialized) {
      return
    }

    console.log('    ↳ Agent Engine configured')
    console.log(`      Model: ${this.config.model}`)
    console.log(`      Auto-fix: ${this.config.autoFix ? 'Enabled' : 'Disabled'}`)

    this.isInitialized = true
  }

  /**
   * Generate code based on a prompt
   */
  async generateCode(request: CodeGenerationRequest): Promise<CodeGenerationResult> {
    console.log(`\n🤖 Agent: Generating code for "${request.prompt}"`)

    // In a real implementation, this would call an AI model API
    // For now, we'll provide a template-based approach
    const code = this.generateTemplateCode(request)

    const result: CodeGenerationResult = {
      code,
      filePath: request.filePath || this.suggestFilePath(request),
      explanation: `Generated code based on prompt: ${request.prompt}`,
      imports: this.extractImports(code)
    }

    console.log(`  ✓ Code generated: ${result.filePath}`)
    return result
  }

  /**
   * Apply code generation result to a file
   */
  async applyCode(result: CodeGenerationResult, targetDir: string): Promise<void> {
    const fullPath = path.join(targetDir, result.filePath)
    const dir = path.dirname(fullPath)

    // Ensure directory exists
    await fs.mkdir(dir, { recursive: true })

    // Write the code
    await fs.writeFile(fullPath, result.code, 'utf-8')

    console.log(`  ✓ Code written to: ${fullPath}`)
  }

  /**
   * Validate generated code
   */
  async validateCode(code: string, language: string = 'typescript'): Promise<{ valid: boolean; errors?: string[] }> {
    // Basic validation - in production, this would use proper linters
    const errors: string[] = []

    if (language === 'typescript' || language === 'javascript') {
      // Check for basic syntax patterns
      if (!code.trim()) {
        errors.push('Code is empty')
      }
    }

    return {
      valid: errors.length === 0,
      errors: errors.length > 0 ? errors : undefined
    }
  }

  /**
   * Auto-fix code issues
   */
  async autoFixCode(code: string, language: string = 'typescript'): Promise<string> {
    if (!this.config.autoFix) {
      return code
    }

    // Basic auto-fixes
    let fixed = code

    // Add semicolons if missing (for TypeScript/JavaScript)
    if (language === 'typescript' || language === 'javascript') {
      // This is a simplified example
      fixed = fixed.trim()
    }

    return fixed
  }

  /**
   * Generate code from templates based on request
   */
  private generateTemplateCode(request: CodeGenerationRequest): string {
    const { prompt, language = 'typescript' } = request

    // Detect what kind of code to generate based on prompt
    if (prompt.toLowerCase().includes('api') || prompt.toLowerCase().includes('endpoint')) {
      return this.generateAPITemplate(prompt)
    } else if (prompt.toLowerCase().includes('component')) {
      return this.generateComponentTemplate(prompt)
    } else if (prompt.toLowerCase().includes('function') || prompt.toLowerCase().includes('util')) {
      return this.generateFunctionTemplate(prompt)
    }

    return this.generateGenericTemplate(prompt)
  }

  /**
   * Generate API endpoint template
   */
  private generateAPITemplate(prompt: string): string {
    return `/**
 * API Endpoint generated by Racer Agent
 * Prompt: ${prompt}
 */

import { NextApiRequest, NextApiResponse } from 'next'

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method === 'GET') {
    // Handle GET request
    return res.status(200).json({
      message: 'API endpoint working',
      timestamp: new Date().toISOString()
    })
  }

  if (req.method === 'POST') {
    // Handle POST request
    const data = req.body
    
    return res.status(200).json({
      message: 'Data received',
      data
    })
  }

  // Method not allowed
  return res.status(405).json({ error: 'Method not allowed' })
}
`
  }

  /**
   * Generate React component template
   */
  private generateComponentTemplate(prompt: string): string {
    const componentName = this.extractComponentName(prompt)
    
    return `/**
 * Component generated by Racer Agent
 * Prompt: ${prompt}
 */

import React from 'react'

interface ${componentName}Props {
  // Add your props here
}

export const ${componentName}: React.FC<${componentName}Props> = (props) => {
  return (
    <div className="${componentName.toLowerCase()}">
      <h1>${componentName}</h1>
      <p>This component was generated by Racer Agent</p>
    </div>
  )
}

export default ${componentName}
`
  }

  /**
   * Generate utility function template
   */
  private generateFunctionTemplate(prompt: string): string {
    return `/**
 * Utility function generated by Racer Agent
 * Prompt: ${prompt}
 */

export function generatedFunction(input: any): any {
  // Implementation generated by AI Agent
  return input
}

export default generatedFunction
`
  }

  /**
   * Generate generic code template
   */
  private generateGenericTemplate(prompt: string): string {
    return `/**
 * Code generated by Racer Agent
 * Prompt: ${prompt}
 */

// TODO: Implement based on prompt
export const generatedCode = {
  // Your implementation here
}

export default generatedCode
`
  }

  /**
   * Extract component name from prompt
   */
  private extractComponentName(prompt: string): string {
    const words = prompt.split(/\s+/)
    for (const word of words) {
      if (word.length > 2 && /^[A-Z]/.test(word)) {
        return word
      }
    }
    return 'GeneratedComponent'
  }

  /**
   * Suggest file path based on request
   */
  private suggestFilePath(request: CodeGenerationRequest): string {
    const { prompt, language = 'typescript' } = request
    const ext = language === 'typescript' ? 'ts' : language === 'javascript' ? 'js' : language

    if (prompt.toLowerCase().includes('api')) {
      return `pages/api/generated.${ext}`
    } else if (prompt.toLowerCase().includes('component')) {
      return `components/Generated.tsx`
    }

    return `lib/generated.${ext}`
  }

  /**
   * Extract import statements from code
   */
  private extractImports(code: string): string[] {
    const importRegex = /import .+ from ['"].+['"]/g
    const matches = code.match(importRegex)
    return matches || []
  }
}

export default AgentEngine
